const THEME_SWITCH = `THEME_SWITCH`;
const MENU_SWITCH = `MENU_SWITCH`;
const SEARCH_SWITCH = `SEARCH_SWITCH`;
const SEARCH_CLOSE = `SEARCH_CLOSE`;
const SEARCH_CHANGE = `SEARCH_CHANGE`;
const SEARCHING = `SEARCHING`;
const WELLCOME_SWITCH = `WELLCOME_SWITCH`;
const TASK_ADD = `TASK_ADD`;
const FILTER_CHANGE = `FILTER_CHANGE`;
const TASK_DELETE = `TASK_DELETE`;
const TASK_FIXED = `TASK_FIXED`;
const TASK_DONE = `TASK_DONE`;
const TASK_EDIT = `TASK_EDIT`;
const MODAL_SWITCH = `MODAL_SWITCH`;
const MORE_SWITCH = `MORE_SWITCH`;
const MORE_CLOSE = `MORE_CLOSE`;

export {
  THEME_SWITCH,
  MENU_SWITCH,
  SEARCH_SWITCH,
  SEARCH_CLOSE,
  SEARCH_CHANGE,
  SEARCHING,
  WELLCOME_SWITCH,
  TASK_ADD,
  FILTER_CHANGE,
  TASK_DELETE,
  TASK_FIXED,
  TASK_DONE,
  TASK_EDIT,
  MODAL_SWITCH,
  MORE_SWITCH,
  MORE_CLOSE
};
