enum ActionTypes {
  THEME_SWITCH = `THEME_SWITCH`,
  MENU_SWITCH = `MENU_SWITCH`,
  SEARCH_SWITCH = `SEARCH_SWITCH`,
  SEARCH_CLOSE = `SEARCH_CLOSE`,
  SEARCH_CHANGE = `SEARCH_CHANGE`,
  SEARCHING = `SEARCHING`,
  WELCOME_SWITCH = `WELCOME_SWITCH`,
  TASK_ADD = `TASK_ADD`,
  FILTER_CHANGE = `FILTER_CHANGE`,
  TASK_DELETE = `TASK_DELETE`,
  TASK_FIXED = `TASK_FIXED`,
  TASK_DONE = `TASK_DONE`,
  TASK_EDIT = `TASK_EDIT`,
  MODAL_SWITCH = `MODAL_SWITCH`,
  MORE_SWITCH = `MORE_SWITCH`,
  MORE_CLOSE = `MORE_CLOSE`
}

export {
  ActionTypes
};
